/* automatically generated by rust-bindgen 0.69.1 */

use std::ffi::{c_int, c_long};

extern "C" {
    // int dbgen(long* scale_, int* step_, long *children_, int *table_) {
    pub fn dbgen(
        scale: *const c_long,
        step: *const c_int,
        children: *const c_long,
        table: *const c_int,
    ) -> ::std::os::raw::c_int;
}
